<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\DnSpyCommon.props" />
  <PropertyGroup>
    <AssemblyName>dnSpy.SecurityAnalysis.x</AssemblyName>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\dnSpy.snk</AssemblyOriginatorKeyFile>
    <OutputPath>..\..\dnSpy\dnSpy\bin\$(Configuration)\</OutputPath>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
    <ProjectReference Include="..\..\dnSpy\dnSpy.Contracts.DnSpy\dnSpy.Contracts.DnSpy.csproj" />
    <ProjectReference Include="..\..\dnSpy\dnSpy.Contracts.Logic\dnSpy.Contracts.Logic.csproj" />
  </ItemGroup>
</Project>
